### PR TITLE
Wysiwyg

### PR DESCRIPTION
**Pull request by Devp00l**
What you see is what you get :)

You can now see a picture of the screen on your device and you can enable auto refresh now :)

Through this change I also refactored the hole app.

### CODE REVIEW

**Comment by aparedero** [comment]
@Devp00l what do I need to compile your android app, Gradle and whole Android SDK?

Thank you for your effort.

PS: I'm just a curious one who discovered short time ago this app

**Comment by Sur3** [comment]
@Devp00l I suspect this change also changes the protocol, can you update doc/protocol.txt accordingly to state how the uinput-driver networktablet communicates with the gfxtablet app?!

**Comment by Sur3** [comment]
@Devp00l Ok I checked that pr, it works fine, but also changes functionality quite a lot, it's pretty usefull for remote controlling some backend PC and the last drawing stripe shown is usefull for accurate drawing. BUT it seems to remove the fullscreen mode?! And also it seems not possible to use an image or black or white as background anymore instead of the remote screen?!

**Comment by Devp00l** [comment]
@aparedero

**Comment by Devp00l** [comment]
Sorry for the late reply everybody.
@aparedero I compiled it the android app via the sdk and tested it successful on 3 different devices (the virtual android device hasn't worked for me)

@Sur3 Yes it removes a lot of the old functionality because didn't made sense to keep it. I also assume that this PR will never be merged in the main repository as it changes a lot, but this PR will increase the visibility for my changes, which really take the app to a new level. But I will update the `protocol.txt` when I work again on this side project.

**Pull request closed without merging**
