### PR TITLE
added multi-monitor support

### PR DESCRIPTION
**Pull request by joschuck**
Hi,

since I am using a multi-monitor setup with different solutions, I added some basic multi monitor support (for X11 server - you need x11 dev libraries to compile). You can use your tablet as mouse for a specific screen (use option -s) only. You can also define a rectangular area on the host screen. This comes in very handy when you want to draw stuff - without the fear to mess up your desktop on another screen. Options are:
-s SCREEN_ID
for rectangular frame:
-w width
-h height
-x horizontal-offset
-y vertical-offset

Greetings
joschuck

### CODE REVIEW

**Comment by ayberkozgur** [comment]
Other than the issue above, the PR seems to work correctly.

**Comment by jpotier** [comment]
So when will this be pulled in the main repo?

**Comment by techtonik** [comment]
@jpotier may be no sooner than when conflicts are resolved.

**Comment by Deadolus** [comment]
I resolved the conflicts and created a pull request on joschuck's repository for him to merge my changes. 
However, there seems to be an error in calculating x/y-offsets and I had to add some custom offsets for his patch to actually track my monitors. 
This being said, I would really like to see multiple monitor support in the main app in the future. 
Thank you very much for creating this app - exactly what I needed.

**Pull request closed without merging**
