### PR TITLE
simple windows driver

### PR DESCRIPTION
**Pull request by wech71**
Hi,

based on your uinput driver I've created something similar for windows.

As windows does not support simply injecting pressure information into the event queue, I've omitted this for now. But instead have built two binaries, one working like the original, and another one, which ignores the normal touch events for mouse clicks, but instead uses pressure information to enable touch moves to just move the mouse while pressing harder with the finger sends the mouse down information so it starts drawing.

For pressure information a HID input driver would be necessary. This will probably make pressure information work in GIMP too.

But for now this is better than nothing I guess.

Thanks for this nice project und greetings from germany

```
christoph
```

### CODE REVIEW

**Comment by Blooface** [comment]
I need instructions!! I"m super confused what I'm suppose to do.

**Comment by Nesh108** [comment]
@Blooface: are you talking about my version? Or wech71's?

**Comment by harraps** [comment]
Ok so only the driver-win32-hover-touch-enable.exe worked for me, I can move my pointer around that's cool ! But I cannot draw with it. My pointer just moves around. I have to press the left mouse button to actually do something.

**Comment by blackcrack** [comment]
would be nice, if exist 2 "buttons" at bottom of the touch-paneel for pressing the right or left button.
from bottom to up , maybe 10-12% of the screen.
=====|=====  like something : http://www.blackysgate.net/files/upload/diffrentpictures/toutchpadsurface.png

this would grate for all surfaces in Android for all Windows, because, 
whith this L&R-Mousepads can controlling it directly, 
in the middle, the red lines can be the configuration-dialogue.

**Comment by wech71** [comment]
@harraps  please try https://github.com/wech71/GfxTablet/blob/binaries/driver-win32.exe instead. The hover-touch-enabled exe you are currently using, tries to distinuish between touch and press, which does not seem to work on your tablet (only tested with a nexus 7) while the driver-win32.exe recognizes every touch as click.

@blackcrack Nice idea. Unfortunately, for this to work, the android application would have to be changed, and I just don't have any time at hands to improve either part. Sorry

**Comment by harraps** [comment]
@wech71 between both only the driver-win32-hover-touch-enable.exe is actually doing something... the driver-win32.exe neither register mouse input nor mouse movement. It doesn't do anything.

**Comment by blackcrack** [comment]
wech71 maybe would be nice if the app use something like an "skinning" with an frames-file and an picture/css which define the different space on the screen for different tasks , so an own folder with different layouts for the touchscreen/surface :) for use as enhancement touchpad for the computer (like at the notebook), or use as define Application-Stylus-Pen workspace (like in gimp, the picture window only - controlling by the systray-icon in winnt , (selecting the mode, klicked window, Selected/ fixed/single (like gimp.exe) exe file&/Programmtread or fullscreen on/by/at the Driver/(Server for the app in Winnt))
... as suggestion.. for have a possible for different areas of application .. with an "pluginsystem" and therewith makes interesting for many other application areas and i bet, many other developers want work with, because therewith, with the Surface-plugin/skin-surface-system makes more interesting for other things.. one surface for the pen and one surface as touch pad for the computer and therewith start it with more enhancement and specific possibility's.. for other things.. in private and industry .. and therewith can it be comes more developers and helping hands ;) Because, you can use your handy or tablet as touchpad with you Office computer ;) and by side can you switch to an other "surface and can use just this pad/handy for grafics-applications and with the mouse (on the table) can you selecting and controlling the systray driver.. .. 

best regards
Blacky

**Comment by madrig88** [comment]
After the last windows update(12-8-2015), the driver does not work at all.

**Comment by SuicSoft** [comment]
Will it work with Windows 10 64-bit and Nexus 9.It works in Linux with Nexus 9 but I am going to test the Windows driver.Is it a kernel mode driver

**Comment by madrig88** [comment]
it was working for me on Windows 10 until the patch Tuesday in December. I haven't had it working since. I had to find a different solution. When this one is working again I will be coming back.

**Comment by PTEB** [comment]
@wech71 I was unable to use your program driver-win32-hover-touch-enabled.exe or driver-win32.exe. I was originally getting an net socket error.. But after using Nesh108's program yours now runs.. But the input does not pass through. 

@madrig88 I was able to get it working on Windows 10 64bit today. My System is up to date. What was the different solution you used?

@Nesh108 I used a Android (4.4.2) Samsung Galaxy Note 10.1 2014 Edition(Model No. SM-P600) tablet running GfxTablet 1.4. 
Like i said to madrig88 im running Windows 10 but more specifically.
Edition: Windows 10 Pro.
Version: 1511
OS Build: 10586.164
Type: 64-Bit
@Nesh108, your GfxTablet_WindowsDriver-v1.1.exe version works a dream (I did run it in administration mode) for me because i am left handed so i can use the tablet as an input with the stylus and use my right hand on the mouse to click when i need to actually draw. I am drawing in Paint.net. 
My screen resolution is 1920x1080 on my PC which works great because by default that is screen resolution on the Samsung Galaxy 2014 so scaling is not an issue. 
Thankyou for hard work.
@Nesh108 unfortunately your GfxTablet_WindowsDriver-blackcrack2.exe which was the only other one still available on dropbox seems to have the middle mouse button always held in.

It would be great to see a checkbox option added to your program to be able to select whether touch on the tablet is counted as a mouse click 
OR it has to be bound to a key or mouse input on startup.
This would help people who aren't left handed =D.
As well as a right click option on your program in the windows tray to be able to view options/exit.

Thanks for your hard work guys keep it up!

**Comment by PTEB** [comment]
Ok...weird..now the GfxTablet_WindowsDriver-blackcrack2.exe is working perfectly (left mouse click is not always down) and the GfxTablet_WindowsDriver-v1.1.exe always has the mouse left click enabled.. but its not consistent and i can't seem to fault what is happening. So odd.. Also the middle click issue has disappeared..

**Comment by alphaCodeo** [comment]
Hi, I ran driver-win32-hover-touch-enabled.exe. There was no window but I'm pretty sure it's supposed to be like that(it appeared in the processes in the Task Manager). I then ran the GfxTablet app and set the Recipient Host to my computer's host name. Nothing happens. At all. No matter whether I run GIMP or run nothing, tapping and dragging don't move anything.

**Comment by alphaCodeo** [comment]
I'm using an ASUS K00E(FonePad 7). Old, I know, but it works ok

**Comment by wech71** [comment]
Have you tried to disable the windows firewall? Maybe it is blocking requests. Also the tablet has to be in the same network as the laptop and some routers (e.g. AVM fritz.box) disable communication between devices when connected to some kind of guest network.

UDP Port 40118 has to be open for incoming connections on the laptop for this to work.

**Comment by alphaCodeo** [comment]
I'll have to check the firewall, but I'm fairly sure it's off. No guest network, but tablet is on 5-GHz network and computer is wired. Does that affect anything? I'll also have to check the port, but I think it's clear.

**Comment by wech71** [comment]
This may be the problem.  Maybe your router prevents access from the 5GHz wifi network to wired devices.

The same situation worked in my network, but I can't tell if your router behaves differently.

**Comment by Izzmo** [comment]
How can I debug this? I'm unable to get it to work either. I have a Surface Pro 2 trying to connect to a Windows 10 PC.

Follow-up question, is there no way to create a client-host relationship running the app in both places to connect to each other?

**Comment by Nesh108** [comment]
@Izzmo what kind of app are you using on the Surface Pro 2? As far as I remember (it has been quite long ago) the app works on Android and the driver on windows/linux. Is your Surface Pro 2 running Android?

Anyway, to debug the whole thing, install Wireshark and check for UDP packets coming from the IP address of the tablet.

**Comment by Izzmo** [comment]
@Nesh108 I am interfacing from my Surface Pro 2 to Windows 10 Desktop PC. The signal is going out on the surface pro 2.. but not coming in on the PC. I think there must be an issue with the driver, I'm not positive.

**Comment by Nesh108** [comment]
@Izzmo yeah but what OS are you running on the Surface Pro 2? And what program are you running there? Because if you are trying to run this driver on it, it won't work, the reason being that this driver is receiving the data not sending it.

**Comment by Izzmo** [comment]
@Nesh108 It is running Windows 10 on the Pro 2 as well, sorry for the confusion.

**Comment by SuicSoft** [comment]
@lzzmo use an Android emultator / virtual machine or install Android on the surface pro if you want to use it as the tablet

**Comment by JixunMoe** [comment]
```
GfxTablet app speaks protocol version 2 but driver speaks version 1, please update
GfxTablet driver shut down gracefully
```

Forced the application to be a console app and discovered the above log.

**Comment by gbraad** [comment]
I tried the driver, but stylus input on a Galaxy Tab S6 is not seen as an active stylus on the receiving end, which means applications like MyScript Nebo can not be used.

**Pull request closed without merging**
